
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khfhloynxijcagrqqicq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZmhsb3lueGlqY2FncnFxaWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTc0MzUsImV4cCI6MjA2MTkzMzQzNX0.aRFCAvWo4wDxofO_Nx0LKPq8-Prn4ucXJsK3cmvAYyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true, 
    storage: typeof window !== 'undefined' ? localStorage : null
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Enable realtime subscription by default
// This will be used for the alerts system
supabase.realtime.setAuth(SUPABASE_PUBLISHABLE_KEY);
